### ISSUE TITLE
Record Video withFilter is on plan?

### ISSUE THREAD

**Issue by nightlight9** [baka3k/RecorderIJKPlayerSample#3]
Your lib is pretty awesome. I want to add a filter to my recorded video.  
Is recording video with filter on your dev plan?
or how can I do it to add a filter to my recorded video?

**Comment by baka3k** [comment]
Currently, I'm so busy and do not have the time to do that
However, if you really want that feature, you can consult how the GPUMp4Composer function works
Please refer below url:
```
https://github.com/MasayukiSuda/GPUVideo-android
```

**Comment by nightlight9** [comment]
> Currently, I'm so busy and do not have the time to do that However, if you really want that feature, you can consult how the GPUMp4Composer function works Please refer below url:
> 
> ```
> https://github.com/MasayukiSuda/GPUVideo-android
> ```

thanks for the reply
